load("@bazel_skylib//rules:copy_file.bzl", "copy_file")
load("@rules_pkg//pkg:verify_archive.bzl", "verify_archive_test")

copy_file(
    name = "spk",
    src = "//spk/consul:spk",
    out = "spk.tar",
)

verify_archive_test(
    name = "spk_container_contains_user_unit",
    max_size = 30,
    must_contain = [
        "conf/systemd/pkg-user-consul.service",
    ],
    target = ":spk",
)
