VICTORIA_METRICS_HTTP_LISTEN_ADDR=0.0.0.0:8428
VICTORIA_METRICS_STORAGE_DATA_PATH=/var/packages/victoriametrics/shares/victoriametrics/data/victoria-metrics
VICTORIA_METRICS_RETENTION_PERIOD=14d
VICTORIA_METRICS_MAX_CONCURRENT_REQUESTS=8
VICTORIA_METRICS_MAX_UNIQUE_TIMESERIES=200000
