VMAGENT_HTTP_LISTEN_ADDR=127.0.0.1:8429
VMAGENT_PROMSCRAPE_CONFIG=/var/packages/victoriametrics/shares/victoriametrics/etc/vmagent.yml
VMAGENT_REMOTE_WRITE_URL=http://127.0.0.1:8428/api/v1/write
VMAGENT_REMOTE_WRITE_TMP_DATA_PATH=/var/packages/victoriametrics/shares/victoriametrics/data/vmagent
