#!/bin/sh
# This is synology-devinfra/spk/talospxe/start-stop-status

FORMAT="%F_%T ${1}"
date +"${FORMAT}" >> /var/packages/talospxe/share/sss.log

case "$1" in
    start)
        synosystemctl start pkg-user-bsdp-server.service
        synosystemctl start pkg-user-bsdp-dnsmasq.service
        ;;
    stop)
        synosystemctl stop pkg-user-bsdp-dnsmasq.service
        synosystemctl stop pkg-user-bsdp-server.service
        ;;
    status)
        echo -n pkg-user-bsdp-server; synosystemctl get-active-status pkg-user-bsdp-server.service
        echo -n pkg-user-bsdp-dnsmasq; synosystemctl get-active-status pkg-user-bsdp-dnsmasq.service
        ;;
    log)
        echo ""
        ;;
    restart)
        # not reachable via "sudo systemctl restart talospxe
        ${0} stop && sleep 3 && ${0} start
        ;;
    preflight)
        # not reachable via "sudo systemctl preflight talospxe
        # only via "sudo /var/packages/talospxe/scripts/start-stop-status preflight
        ( set -x  # FIXME
        netstat -panu | grep -E ':(67|68|69|53|80) '
        ls -al /usr/local/lib/systemd/system/pkg-user-bsdp-server.service
        ls -al /usr/local/lib/systemd/system/pkg-user-bsdp-dnsmasq.service
        ls -al /usr/local/lib/systemd/system/pkgctl-talospxe.service
        systemctl list-units | grep pkgctl-talospxe.service
        systemctl list-units | grep pkg-user-bsdp-server.service
        systemctl list-units | grep pkg-user-bsdp-dnsmasq.service
        systemctl list-units | grep bsdp.slice
        )
        ;;
    *)
        echo "Usage: $0 {start|stop|status}" >&2
        exit 1
        ;;
esac

exit 0
